### ISSUE TITLE
not works in console with Russian locale

### ISSUE THREAD

**Issue by matweew** [ootync/Patricks#1]
% ./patricks.php                                                                                                                                                  14:23:25
PHP Fatal error:  Uncaught Exception EPulseAudio::ent_name_404 (@PulseAudio.API.php:107):
    Found an unknown entity: "Модуль"
array (
  'ent' => 'Модуль',
)

  thrown in /home/matveyev/bin/ootync-Patricks-6c1e976/PulseAudio.API.php on line 107

% locale                                                                                                                                                          14:23:28
LANG=ru_UA.UTF-8
LC_CTYPE="ru_UA.UTF-8"
LC_NUMERIC="ru_UA.UTF-8"
LC_TIME="ru_UA.UTF-8"
LC_COLLATE="ru_UA.UTF-8"
LC_MONETARY="ru_UA.UTF-8"
LC_MESSAGES="ru_UA.UTF-8"
LC_PAPER="ru_UA.UTF-8"
LC_NAME="ru_UA.UTF-8"
LC_ADDRESS="ru_UA.UTF-8"
LC_TELEPHONE="ru_UA.UTF-8"
LC_MEASUREMENT="ru_UA.UTF-8"
LC_IDENTIFICATION="ru_UA.UTF-8"
LC_ALL=

**Comment by ootync** [comment]
Will fix soon, thank you!

**Comment by zahrevsky** [comment]
Still not fixed :(

~$ patricks.php
PHP Notice:  Undefined offset: 1 in /usr/local/bin/patricks/PulseAudio.API.php on line 101
PHP Fatal error:  Uncaught Exception EPulseAudio::ent_name_404 (@PulseAudio.API.php:108):
	Found an unknown entity: "Модуль №0"
array (
  'ent' => 'Модуль №0',
)

  thrown in /usr/local/bin/patricks/PulseAudio.API.php on line 108
~$ locale
LANG=ru_UA.UTF-8
LANGUAGE=ru_UA:ru
LC_CTYPE="ru_UA.UTF-8"
LC_NUMERIC="ru_UA.UTF-8"
LC_TIME="ru_UA.UTF-8"
LC_COLLATE="ru_UA.UTF-8"
LC_MONETARY="ru_UA.UTF-8"
LC_MESSAGES="ru_UA.UTF-8"
LC_PAPER="ru_UA.UTF-8"
LC_NAME="ru_UA.UTF-8"
LC_ADDRESS="ru_UA.UTF-8"
LC_TELEPHONE="ru_UA.UTF-8"
LC_MEASUREMENT="ru_UA.UTF-8"
LC_IDENTIFICATION="ru_UA.UTF-8"
LC_ALL=
